### PR TITLE
SQRT fixes (resolves corruption in THPS2)

### LINKED ISSUE #5: Graphical Glitches in Tony Hawk Pro Skater II
The character doesn't seem to animate correctly. This can be seen in the intro movie below and in regular game play. 

Incorrect Rendering with the CoG BIOS:

https://user-images.githubusercontent.com/7118296/141451232-9755bbba-d992-4449-9159-b0005df93afa.mov

Correct Rendering

https://user-images.githubusercontent.com/7118296/141451285-5f3ee8de-6376-4645-be9a-08677df87795.mov

### PR DESCRIPTION
**Pull request by skylersaleh**
- Moved mul dst to r4 so that rd and rm are not the same
- Only add r2 to r1 when the new root would be less than the input
- Fixes https://github.com/Cult-of-GBA/BIOS/issues/5

### CODE REVIEW

**Review by DenSinH — COMMENTED** [review]
I don't think using `r4` is necessary here, `r3` is not used in any other place in that loop, the `ls` change probably is necessary. I can't check this fully though cause I'm on my phone at the moment.

**Comment by DenSinH** [comment]
Yeah the `r4` change is not necessary.

**Comment by skylersaleh** [comment]
The r4 is necessary because of a design quirk of the early ARM processors. While r3 isn't used elsewhere, the mul instruction itself actually reloads Rm and writes Rd for each of its multi cycles. So, if they are the same you will actually be doing the following computation:

v = v\*d[7:0];
v += v\*d[15:8];
v += v\*d[23:16];
v += v\*d[31:24];

Which isn't correct as at each step you are multiplying by the partial result. I don't think most emulators would emulate this HW quirk, but if your emulator does, or you wanted to run this on real HW, it wouldn't work without the r4 change. 

See the following link for more information:

https://stackoverflow.com/questions/33046876/why-cant-the-first-two-arguments-to-the-mul-expression-on-arm7-be-the-same

**Comment by DenSinH** [comment]
Hmmm yeah I googled it again, I thought this quirk was for versions before ARMv4t, but you're right that this is not valid for ARMv4t either. It's probably still better to use r12 instead (scratch register iirc) in order to not have to push/pop an extra register.

**Pull request merged**
